[build]
  publish = "."
  command = "echo 'No build step needed'"

[[redirects]]
  from = "/"
  to = "/examples/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/**/*.js"
  [headers.values]
    Content-Type = "application/javascript"
